this.LivePersonaCardStrings = {};
this.LivePersonaCardStrings.strings = {
  "hoverTargetStrings": {
    "ariaLabel": "Opens Profile Card",
    "ariaLabelWithPersonInfo": "Opens Profile Card for {0}"
  },
  "utilityStrings": {
    "copyToClipboardHelpText": "Ctrl+C (or Command+C on Mac OS), Enter",
    "concatEllipsis": "{0}…"
  },
  "footerSectionStrings": {
    "profileLink": "Show more",
    "feedbackRequestString": "We'd love your feedback"
  },
  "headerSectionStrings": {
    "expandMeetingButton": "View event",
    "editProfile": "Update your profile",
    "closeButtonAccessibilityTitle": "Close",
    "userPhotoAltText": "Photo of {0}",
    "emailButton": "Send email",
    "emailButtonDescription": "Send an email to {0}",
    "chatButton": "Start chat",
    "chatButtonDescription": "Start a chat with {0}",
    "findProfileButton": "Find profile",
    "findProfileButtonDescription": "Find LinkedIn profile for {0}",
    "viewProfileButton": "View profile",
    "viewProfileButtonDescription": "View LinkedIn profile for {0}",
    "distributionListTitle": "Distribution list",
    "privateDistributionListTitle": "Contact list",
    "groupVisibilityPrivate": "Private group",
    "groupVisibilityPublic": "Public group",
    "groupVisibilityPrivateWithGuests": "Private group with guests",
    "groupVisibilityPublicWithGuests": "Public group with guests",
    "groupMembersCount": "{0} members",
    "distributionListWith100OrMoreMembersCount": "99+ members",
    "yammerButtonDescription": "Yammer",
    "teamsButtonDescription": "Teams",
    "conversationsButtonDescription": "Email",
    "filesButtonDescription": "Files",
    "calendarButtonDescription": "Calendar",
    "notebookButtonDescription": "Notebook",
    "sharepointSiteButtonDescription": "Site",
    "plannerButtonDescription": "Planner",
    "meetingJoinOnlineButtonLabel": "Join online meeting",
    "meetingJoinTeamsButtonLabel": "Join the meeting on Teams",
    "meetingLocation": "Location",
    "seeMoreMeetingLocation": "See more about the location",
    "privateGroupJoinButtonLabel": "Request to join",
    "publicGroupJoinButtonLabel": "Join group",
    "privateGroupJoinButtonAttemptPendingLabel": "Sending join request...",
    "publicGroupJoinButtonAttemptPendingLabel": "Joining...",
    "groupLeaveButtonAttemptPendingLabel": "Leaving group...",
    "joinPrivateGroupRequestOptionalMessagePlaceholder": "Optional message to group owner",
    "groupSendPrivateGroupJoinRequestButtonLabel": "Send",
    "groupCancelPrivateGroupJoinRequestButtonLabel": "No thanks",
    "groupJoinButtonRequestSentLabel": "Request to join is pending approval",
    "groupClassification": "({0})",
    "inviteToGroupPopupTitle": "Invite others to this group",
    "inviteToGroupPopupDescription": "Copy and share, or email the link directly to someone in your organization. When recipients click the link, they'll be added to the group.",
    "inviteToGroupPopupCopyButtonLabel": "Copy",
    "inviteToGroupPopupCopyButtonSuccessMessage": "Link copied to clipboard - ready to share",
    "inviteToGroupPopupCopyButtonFailureMessage": "Couldn't copy the URL to the clipboard. Please try again by selecting the link above and pressing Ctrl+C (or Command+C on Mac OS).",
    "inviteToGroupPopupEmailButtonLabel": "Email link",
    "inviteToGroupPopupCloseButtonAriaLabel": "Close",
    "inviteToGroupPopupEmailSubjectFormat": "You're invited to join the \"{0}\" group.",
    "inviteToGroupPopupEmailContentLine1Format": "You were invited to join the Office 365 group \"{0}\".",
    "inviteToGroupPopupEmailContentLine2PublicGroup": "This is a public group. Click the link below to join the group:",
    "inviteToGroupPopupEmailContentLine2PrivateGroup": "This is a private group. Submit a request to the group owner to join the group by clicking the link below:",
    "editPrivateDistributionListSecondaryActionLabel": "Edit list",
    "scheduleMeetingPrivateDistributionListSecondaryActionLabel": "Schedule meeting",
    "secondaryActionsMenuAriaLabel": "Secondary actions menu"
  },
  "meetingHeaderSectionStrings": {
    "unknownMeetingTitle": "Unknown",
    "respondToOccurrence": "This event",
    "respondToSeries": "All events in the series",
    "accept": "Yes",
    "tentativelyAccept": "Maybe",
    "decline": "No",
    "cancel": "Cancel",
    "acceptedResponseStatus": "Yes, I'll attend",
    "tentativelyAcceptedResponseStatus": "I might attend",
    "declinedResponseStatus": "No, I won't attend",
    "acceptOccurrence": "Yes, I'll attend this event",
    "acceptSeries": "Yes, I'll attend all events in the series",
    "tentativelyAcceptOccurrence": "I might attend this event",
    "tentativelyAcceptSeries": "I might attend all events in the series",
    "declineOccurrence": "No, I won't attend this event",
    "declineSeries": "No, I won't attend any events in the series",
    "removeOccurrence": "Remove event",
    "removeSeries": "Remove series",
    "cancelOccurrence": "Cancel event and notify guests",
    "cancelSeries": "Cancel all events in the series and notify guests",
    "addYourResponse": "Add message (optional)",
    "notifyOrganizer": "Notify organizer",
    "send": "Send",
    "save": "Save",
    "edit": "Edit",
    "delete": "Delete",
    "discard": "Discard",
    "youAreOrganizer": "You're the organizer.",
    "personInvitedYou": "{0} invited you.",
    "recurringMeetingTooltip": "This meeting is part of a series"
  },
  "errorBlockStrings": {
    "singleBlockErrorMessage": "Something went wrong.",
    "singleBlockErrorTryAgain": "Try again.",
    "closeButtonAccessibilityTitle": "Click to close the error pane",
    "criticalErrorMessage": "Something went wrong.",
    "criticalErrorDescription": "Please try again later.",
    "criticalErrorTryAgain": "Try again",
    "criticalErrorRetryingMessage": "Working on it...",
    "criticalErrorRetryingDescription": "This shouldn't take long.",
    "criticalErrorFailedRetryMessage": "Still no luck",
    "criticalErrorFailedRetryDescription": "Let us know about this by clicking Send. The error details will be included automatically",
    "criticalErrorFailedRetrySendMessage": "Send",
    "criticalErrorFailedRetryPrivacyPolicyMessage": "Privacy policy"
  },
  "linkedInBlockStrings": {
    "linkedIn": "LinkedIn",
    "education": "Education",
    "seeProfileLinkAlt": "See LinkedIn profile",
    "footer": "Show LinkedIn profile",
    "footerSingleMatch": "Show profile match",
    "footerMultipleMatch": "Show profile matches",
    "seeProfilesLinkAlt": "See LinkedIn profiles"
  },
  "linkedInMultiPreviewStrings": {
    "titleMatches": "{0} possible matches for",
    "severalPossibleMatches": "Several possible matches for {0}",
    "titleMatch": "1 possible match for {0}"
  },
  "linkedInCardStrings": {
    "linkedInCardTitle": "LinkedIn profile",
    "linkedInConnectText": "Connect",
    "linkedInConnectTitle": "Send invitation to connect on LinkedIn",
    "linkedInConnectPendingText": "Pending",
    "linkedInConnectPendingTitle": "Awaiting answer from {0}",
    "linkedInMatchingProfileText": "Matching profile",
    "linkedInProfileMatchedText": "Profile matched",
    "linkedInUndoMatchPendingText": "Undoing profile match",
    "linkedInAcceptInvitationText": "Accept LinkedIn invitation",
    "linkedInAcceptInvitationTitle": "Accept LinkedIn invitation",
    "linkedInNoAvailableInfoTitle": "No available info",
    "linkedInNoAvailableInfoBody": "We can only show selected information from LinkedIn here. There may be more information available on LinkedIn."
  },
  "linkedInBindFlowStrings": {
    "linkedInBindTitle": "Connect your account to see LinkedIn profiles in Office 365",
    "buttonConnect": "Yes, let's go",
    "notOnLinkedIn": "Not on LinkedIn?"
  },
  "linkedInCardBindFlowStrings": {
    "linkedInBindTitle": "Sign in to LinkedIn and we'll show profile info here",
    "buttonConnect": "Yes, let's go",
    "notOnLinkedIn": "Not on LinkedIn?"
  },
  "userInfoBlockStrings": {
    "title": "Contact",
    "seeMore": "See more contact information",
    "footer": "Show more",
    "phoneNumber": "Phone number {0}",
    "emailAddress": "Email {0}",
    "officeLocation": "Office location {0}",
    "chatUrl": "Chat in Messenger"
  },
  "brandInfoBlockStrings": {
    "subscribeLabel": "Subscribe",
    "unsubscribeLabel": "Unsubscribe",
    "nearbyLabel": "Nearby",
    "openTodayLabel": "Hours: {0}-{1}",
    "isYourBrand": "Is this your business?",
    "gotoWebsite": "Go to website",
    "shopNow": "Shop now",
    "bookNow": "BookNow",
    "signUp": "SignUp",
    "learnMore": "Learn more.",
    "feedback": "Feedback",
    "suggestAnEdit": "Suggest an edit",
    "emailUsAt": "Email us at: {0}",
    "emailSentFrom": "Email sent from: {0}",
    "officialWebsite": "Official website",
    "photosBlockTitle": "Photo",
    "photosBlockAltTitle": "See more photos",
    "showMorePhotos": "Show more photos"
  },
  "brandFeedbackViewStrings": {
    "title": "Feedback about this card?",
    "likeItOption": "Like it",
    "dontLikeItOption": "Don't like it",
    "sendFeedbackLabel": "Send feedback",
    "commentTitle": "Comments or suggestions",
    "helpful": "This is helpful",
    "missing": "Something is missing",
    "wrong": "Something is wrong",
    "useless": "This isn't useful",
    "submit": "Submit",
    "titleSubmit": "Thank you for helping us make Outlook better!",
    "feedbackMessage": "Your feedback has been submitted to the development team and will help us shape the product in future.",
    "feedbackContentLimit": "500 characters limit",
    "successOK": "OK",
    "textareaLimitLabel": "500 characters limit",
    "privacyNotice": "Privacy notice"
  },
  "brandEditSuggestionStrings": {
    "suggestEditTitle": "Suggest an edit",
    "suggestEditRemark": "Please mark incorrect information.",
    "submitEditsLabel": "Submit edits",
    "brandName": "Name",
    "website": "Website",
    "emailAddress": "Email address",
    "phoneNumber": "Phone number",
    "nearbyLocation": "Nearby locations",
    "nearbyLocationDescription": "This information is incorrect.",
    "wrongProfile": "Wrong profile",
    "wrongProfileDescription": "The profile displayed does not match the sender of the email.",
    "editContentHint": "Please describe what was wrong…",
    "textAreaLimitLabel": "500 characters limit",
    "feedbackLinkLabel": "Leave some general feedback about the card",
    "noMistakeLabel": "No mistake?"
  },
  "managerBlockStrings": {
    "title": "Reports to",
    "titleYou": "Your manager",
    "showOrg": "See organization",
    "footer": "Show organization",
    "userPhotoAltText": "Photo of {0}"
  },
  "directReportsBlockStrings": {
    "title": "Direct reports ({0})",
    "titleYou": "Your directs ({0})",
    "showOrg": "See organization",
    "footer": "Show organization"
  },
  "navigationBarStrings": {
    "backButtonText": "Back",
    "backButtonAltText": "Back to {0}",
    "personaCard": "Profile card",
    "personaCardForPersona": "Profile card for {0}"
  },
  "meetingsBlockStrings": {
    "title": "Upcoming events",
    "noUpcomingMutualMeetingsDescription": "No upcoming mutual events planned."
  },
  "meetingsViewStrings": {
    "title": "Events",
    "upcomingMeetingsTitle": "Upcoming events",
    "pastMeetingsTitle": "Past events",
    "noUpcomingMutualMeetingsDescription": "No upcoming mutual events planned.",
    "noPastMutualMeetingsDescription": "No past mutual events were found.",
    "upcomingMeetingsInfoTooltip": "More details",
    "upcomingMeetingsInfoPopupDescription": "These are the upcoming events you share with this person.",
    "pastMeetingsInfoTooltip": "More details",
    "pastMeetingsInfoPopupDescription": "These are the past events you shared with this person."
  },
  "documentsBlockStrings": {
    "title": "Files",
    "footer": "Show more files",
    "modified": "Modified",
    "shared": "Shared",
    "emailed": "Emailed",
    "timeActionFormat": "{0} {1}",
    "showMoreDocs": "See more files",
    "documentIsShared": "Shared document",
    "noDocumentsDescriptionYou": "Seems like you haven't stored any files in Office 365. When you upload files to OneDrive or SharePoint, you'll also see them here.",
    "noDocumentsDescriptionYouConsumer": "We couldn't find any files.",
    "noDocumentsDescriptionFormat": "Seems like {0} hasn’t shared any files with you lately.",
    "noDocumentsLinkYou": "Go to your OneDrive",
    "noDocsLinkContext": "Show documents from Office 365",
    "noDocsDescriptionSite": "We couldn't find any recent documents by {0} in this site.",
    "noDocsDescriptionGroup": "We couldn't find any recent documents by {0} in this group.",
    "noDocsDescriptionSiteYou": "We couldn't find any recent documents by you in this site.",
    "noDocsDescriptionGroupYou": "We couldn't find any recent documents by you in this group."
  },
  "emailsBlockStrings": {
    "title": "Email",
    "footer": "Show more email",
    "sentLabelFormat": "Sent: {0}",
    "senderLabelFormat": "From: {0}",
    "subjectLabelFormat": "Subject: {0}",
    "summaryLabelFormat": "Email message: {0}",
    "unread": "Unread",
    "timeActionFormat": "{0} {1}",
    "noEmails": "We couldn't find any emails between you and {0}.",
    "noEmailsFromYou": "We couldn't find any email messages.",
    "noEmailsMeeting": "We couldn't find any email messages.",
    "showMoreEmails": "See more email",
    "youSenderLabel": "You",
    "noSubjectLabel": "(No subject)",
    "noBodyLabel": "(No message text)"
  },
  "groupConversationsBlockStrings": {
    "title": "Email",
    "footer": "Show more group emails",
    "timeActionFormat": "{0} {1}",
    "noGroupConversations": "We couldn't find any emails for this group.",
    "showMoreGroupConversations": "See more emails",
    "noTopicLabel": "(No topic)",
    "noPreviewLabel": "(No message text)",
    "sentLabelFormat": "Sent: {0}",
    "senderLabelFormat": "From: {0}",
    "subjectLabelFormat": "Subject: {0}",
    "previewLabelFormat": "Email preview: {0}",
    "groupConversationLink": "{0}/owa/?path=/group/{1}/mail&exsvurl=1&ispopout=0&ConvID={2}"
  },
  "groupConversationsViewStrings": {
    "title": "Email",
    "emailed": "Emailed",
    "timeActionFormat": "{0} {1}",
    "groupConversationGroupToday": "Today",
    "groupConversationGroupYesterday": "Yesterday",
    "groupConversationGroupLastWeek": "Last week",
    "groupConversationGroupOlder": "Older"
  },
  "groupMembersBlockStrings": {
    "title": "Members",
    "countTitle": "Members ({0})",
    "distributionListWith100OrMoreMembersCountTitle": "Members (99+)",
    "footer": "Show more members",
    "noMembers": "No members found for this group",
    "showMembers": "Show members",
    "groupOwner": "(Group Owner)",
    "userPhotoAltText": "Photo of {0}"
  },
  "groupMembersViewStrings": {
    "groupOwner": "(Group owner)",
    "membersTitle": "Members",
    "ownersTitle": "Owners",
    "goToGroupMembers": "Go to group members",
    "leftoverMembersFormat": "+{0} others",
    "leftoverMembersWhenTotalNumberIsUnknownFormat": "{0}+ others"
  },
  "privateDistributionListNotesBlockStrings": {
    "title": "Notes"
  },
  "userInfoViewStrings": {
    "title": "Contact",
    "manager": "Manager",
    "userPhotoAltText": "Photo of {0}"
  },
  "brandUnsubscribeResultViewStrings": {
    "unsubscribeLabel": "Unsubscribe",
    "unsubscribeButtonLabel": "Continue",
    "cancelLabel": "Cancel",
    "confirmHeader": "Stop getting newsletters from {0}?",
    "confirmBody": "You´ll be taken to this page to unsubscribe from their mailing list.",
    "loadingLabel": "Working on it",
    "successHeader": "Request sent",
    "successBody": "We have successfully asked {0} to remove you from their mailing list. This change may take up to 48 hours.",
    "successOK": "OK"
  },
  "inferredContactStrings": {
    "title": "Here's some additional information we found:",
    "phoneLabel": "Phone",
    "emailLabel": "Email",
    "companyLabel": "Company",
    "jobTitleLabel": "Job title",
    "prompt": "Is this information correct?",
    "yes": "Yes",
    "no": "No",
    "acceptFeedback": "Thanks. We'll keep showing you this information.",
    "rejectFeedback": "Thanks for your feedback!"
  },
  "orgChartViewStrings": {
    "title": "Organization",
    "infoDescription": "The information is collected from other systems. To make changes, contact your system administrator.",
    "infoTooltip": "More details",
    "userPhotoAltText": "Photo of {0}"
  },
  "documentsViewStrings": {
    "title": "Files",
    "modified": "Modified",
    "shared": "Shared",
    "emailed": "Emailed",
    "timeActionFormat": "{0} {1}",
    "oneDriveTitleFormat": "{0}'s OneDrive",
    "siteTitleFormat": "{0} Site",
    "secondaryActionStrings": {
      "secondaryActions": "More options",
      "copyLink": "Copy link",
      "shareEmail": "Share by email",
      "download": "Download",
      "goToLocation": "Go to location",
      "openEmail": "Open email",
      "shareByEmailSubject": "Have a look at '{0}'",
      "shareByEmailFirstLine": "Hi,",
      "shareByEmailSecondLine": "Have a look at '{0}'",
      "groupActionAddMembers": "Add members",
      "groupActionInviteOthers": "Invite others",
      "groupActionJoinGroup": "Join group",
      "groupActionLeaveGroup": "Leave group",
      "groupActionEditGroup": "Edit group",
      "personActionAddToContacts": "Add to contacts",
      "personActionViewProfile": "See more"
    }
  },
  "emailsViewStrings": {
    "title": "Email",
    "emailed": "Emailed",
    "timeActionFormat": "{0} {1}",
    "emailGroupToday": "Today",
    "emailGroupYesterday": "Yesterday",
    "emailGroupLastWeek": "Last week",
    "emailGroupOlder": "Older"
  },
  "meetingsStrings": {
    "oneDayTimeSpanFormat": "{0}, {1} - {2}",
    "oneDayNoDurationTimeSpanFormat": "{0} {1}",
    "multiDayTimeSpanFormat": "{0}, {1} to {2}, {3}",
    "oneDayAllDayTimeSpanFormat": "{0} (all day)",
    "multiDayAllDayTimeSpanFormat": "{0} to {1}"
  },
  "groupSubscriptionBlockStrings": {
    "groupOwner": "Owner",
    "joinedGroup": "Joined",
    "notJoinedGroup": "Not Joined",
    "followGroupInInbox": "Follow in inbox"
  },
  "locationMapBlockStrings": {
    "map": "Map"
  },
  "locationBlockStrings": {
    "information": "Information"
  },
  "timeFormatStrings": {
    "amPartOfDay": "AM",
    "amPartOfDayLowercase": "am",
    "amPartOfDayAbbreviated": "A",
    "amPartOfDayLowercaseAbbreviated": "a",
    "pmPartOfDay": "PM",
    "pmPartOfDayLowercase": "pm",
    "pmPartOfDayAbbreviated": "P",
    "pmPartOfDayLowercaseAbbreviated": "p",
    "todayShort": "{H}:{M} {AMPM}",
    "todayDayShort": "Today",
    "todayLong": "Today at {H}:{M} {AMPM}",
    "yesterdayShort": "Yesterday",
    "yesterdayLong": "Yesterday at {H}:{M} {AMPM}",
    "tomorrowShort": "Tomorrow",
    "comingSundayShort": "Sunday",
    "comingMondayShort": "Monday",
    "comingTuesdayShort": "Tuesday",
    "comingWednesdayShort": "Wednesday",
    "comingThursdayShort": "Thursday",
    "comingFridayShort": "Friday",
    "comingSaturdayShort": "Saturday",
    "sundayShort": "Sun",
    "mondayShort": "Mon",
    "tuesdayShort": "Tue",
    "wednesdayShort": "Wed",
    "thursdayShort": "Thu",
    "fridayShort": "Fri",
    "saturdayShort": "Sat",
    "daysAgoShort": "1->2::One day ago||2->INF::{#D} days ago",
    "daysAgoLong": "1->2::One day ago||2->3::Two days ago||3->INF::{#D} days ago",
    "generic": "{MO}/{D}/{Y}",
    "monthAndDate": "{MO}/{D}",
    "monthNameAndDate": "{MONTH} {D}",
    "defaultDateFormat": "MM/dd/yyyy",
    "default12HourClockTimeFormat": "hh:mm tt",
    "default24HourClockTimeFormat": "HH:mm",
    "dayNameWrapper": "ddd {0}"
  },
  "monthNamesStrings": {
    "january": "January",
    "february": "February",
    "march": "March",
    "april": "April",
    "may": "May",
    "june": "June",
    "july": "July",
    "august": "August",
    "september": "September",
    "october": "October",
    "november": "November",
    "december": "December"
  },
  "monthShortNamesStrings": {
    "january": "Jan",
    "february": "Feb",
    "march": "Mar",
    "april": "Apr",
    "may": "May",
    "june": "Jun",
    "july": "Jul",
    "august": "Aug",
    "september": "Sep",
    "october": "Oct",
    "november": "Nov",
    "december": "Dec"
  },
  "popupMessageStrings": {
    "closePopupButtonText": "Got it",
    "popupOpenedScreenReaderMessage": "Dialog opened"
  },
  "favoritePersonButtonStrings": {
    "addToFavoritesText": "Add to favorites",
    "removeFromFavoritesText": "Remove from favorites"
  },
  "feedbackControlStrings": {
    "sendFeedback": "Send us your feedback"
  },
  "profilePhotoPicker": {
    "cancel": "Cancel",
    "upload": "Upload a new photo",
    "uploadHeader": "Change photo",
    "inProgress": "In progress...",
    "remove": "Remove",
    "close": "Done",
    "apply": "Apply",
    "imageTooSmall": "This photo is very small and may look blurry on larger screens. Do you have a bigger one?",
    "notAnImage": "Hmm... that file format didn't work. Try using one of the more common image formats, such as .jpg, .png, or .gif.",
    "somethingWentWrong": "Something went wrong and we couldn't apply your changes right now. Please try again later.",
    "unsupportedBrowser": "Your browser does unfortunately not appear to support HTML5",
    "dropZone": "Drag your photo here",
    "zoom": "Zoom",
    "zoomOut": "Zoom out",
    "zoomIn": "Zoom in",
    "success": "Successfully set profile photo"
  },
  "skypeWebChatStrings": {
    "loading": "Just a moment…"
  },
  "meetingAttendeesBlockStrings": {
    "title": "Attendees ({0})",
    "seeMoreAttendees": "See more attendees",
    "accepted": "Accepted",
    "noreply": "No reply",
    "declined": "Declined",
    "tentative": "Tentative",
    "numAttendeesAccepted": "{0} of {1} attendees have accepted",
    "allAttendeesAccepted": "All attendees have accepted",
    "noAttendeesAccepted": "No attendees have accepted"
  },
  "meetingInsightsBlockStrings": {
    "title": "Insights"
  },
  "meetingInsightsViewStrings": {
    "title": "Insights"
  },
  "copyButtonStrings": {
    "copied": "Copied"
  },
  "immersiveProfileStrings": {
    "navigationMenuAriaLabel": "Expanded profile pane navigation menu for {0}",
    "closeButtonAccessibilityTitle": "Close",
    "closeButtonAccessibilityAriaLabel": "Close expanded profile view",
    "immersiveProfileHeaderSectionStrings": {
      "ariaLabel": "Expanded profile pane for {0}",
      "noUserPhoto": "User photo not available :(",
      "userPhotoAriaLabel": "Image of {0}",
      "message": "Message",
      "chat": "Chat",
      "call": "Call",
      "callMobile": "Call mobile",
      "sendMessageTooltip": "Send email to {0}",
      "startChatTooltip": "Start chat with {0}",
      "startPhoneCall": "Start a phone call",
      "moreActions": "More actions",
      "copy": "Copy to clipboard",
      "back": "Back",
      "backToPerson": "Back to {0}",
      "addToContacts": "Add to contacts",
      "viewWorkProfile": "Go to profile"
    },
    "immersiveProfileAboutSectionStrings": {
      "title": "About",
      "header": "More about {0}",
      "noAboutTitle": "Seems like {0} hasn't added any information yet.",
      "noAboutTitleMePage": "Seems like you haven't added any information.",
      "noAboutBody": "It looks like this person hasn't shared too much about themselves with Office 365 yet. Maybe next time you speak to them, you can remind them to update their profile!",
      "noAboutBodyMePage": "Your profile is a great opportunity to let others know more about you and what you're working on right now. Add projects, skills, education history and more.",
      "updateProfileLinkInText": "Update your profile",
      "immersiveProfileAboutMeStrings": {
        "aboutMe": "About me"
      },
      "immersiveProfileBirthdayStrings": {
        "birthday": "Birthday"
      },
      "immersiveProfileTaxonomicStrings": {
        "projects": "Projects",
        "projectsDescription": "Here are some of the projects I've worked on",
        "skills": "Skills and expertise",
        "skillsDescription": "Here are some of my personal skills",
        "askAboutDescription": "You can also ask me about",
        "schools": "Schools and education",
        "schoolsDescription": "These are the schools I've gone to",
        "interests": "Interests and hobbies",
        "interestsDescription": "Here's what I like doing in my free time"
      }
    },
    "immersiveProfileGroupConversationsSectionStrings": {
      "shortTitle": "Email",
      "groupConversationsTitle": "Recent email",
      "emptyGroupConversationsMessage": "We couldn't find any email messages for this group.",
      "groupConversationsLoadingMessage": "We're getting the email messages for you. This shouldn't take long."
    },
    "immersiveProfileGroupOverviewSectionStrings": {
      "title": "About",
      "immersiveProfileGroupOverviewStrings": {
        "groupOverview": "About this group",
        "description": "Description",
        "groupMembers": "Group members",
        "groupWorkloads": "Workloads",
        "viewAllMembershipRequests": "View all"
      },
      "immersiveProfileGroupMembersStrings": {
        "goToGroupMembersButton": "See all {0} members"
      },
      "immersiveProfileGroupWorkloadsStrings": {
        "yammer": "Yammer",
        "teams": "Teams",
        "conversations": "Mail",
        "calandar": "Calendar",
        "files": "Files",
        "notebook": "Notebook",
        "sharepointSite": "Site",
        "planner": "Planner"
      }
    },
    "immersiveProfileGroupMembersSectionStrings": {
      "title": "Members",
      "sectionHeader": "All members",
      "immersiveProfileGroupMembersStrings": {
        "ownersTitle": "Owners",
        "membersTitle": "Members",
        "nameTitle": "Name",
        "designationTitle": "Designation",
        "roleTitle": "Role",
        "ownerRole": "Owner",
        "memberRole": "Member",
        "demoteMemberDropdown": "Remove owner status",
        "promoteMemberDropdown": "Promote to owner",
        "membershipRequestDateFormat": "{WEEKDAY} {MO}/{D}/{Y} {H}:{M} {AMPM}",
        "pendingMembershipRequestsTitle": "{0} Pending requests to join",
        "pendingMembershipRequestsTitleSingular": "1 Pending request to join",
        "pendingMembershipRequestsApprovingTitle": "Approving all pending membership requests...",
        "goToGroupMembersButton": "See all {0} members",
        "approveMembershipRequestButton": "Approve",
        "approveAllMembershipRequests": "Approve all",
        "membershipRequestedBy": "Requested by",
        "approveAllMembershipRequestSucceed": "All requests resolved.",
        "approveAllMembershipRequestFailed": "Unable to approve these pending member requests. Please try again.",
        "approvingMembershipRequest": "Approving...",
        "membershipRequestApprovalFailed": "Failed.",
        "membershipRequestApprovalSucceeded": "Approved",
        "newMemberIndicator": "New"
      }
    },
    "immersiveProfileGroupFilesSectionStrings": {
      "title": "Files",
      "goToGroupFilesButton": "See all files"
    },
    "immersiveProfileContactSectionStrings": {
      "title": "Contact",
      "header": "Contact or learn about {0}",
      "immersiveProfileContactButtonStrings": {
        "addContact": "Add to contacts",
        "addingToContacts": "Working on it...",
        "successfullyAddedContact": "Success",
        "failedToAddContact": "Error",
        "editContact": "Edit contact",
        "editInContacts": "Edit in contacts",
        "somethingWentWrong": "Something went wrong",
        "pleaseTryAgain": "It's not you, it's us. Please try again.",
        "sectionAriaLabel": "Contact management actions",
        "addContactInformation": "Add contact information"
      },
      "immersiveProfileContactInfoStrings": {
        "contactInformation": "Contact information",
        "mobilePhone": "Mobile",
        "workPhone": "Work phone",
        "homePhone": "Home phone",
        "otherPhone": "Other phone",
        "otherFax": "Other fax",
        "homeFax": "Home fax",
        "businessFax": "Business fax",
        "pager": "Pager",
        "organization": "Organization phone",
        "workEmail": "Work email",
        "otherEmail": "Email",
        "chat": "Chat",
        "copyPhoneNumberToClipboard": "Copy phone number",
        "copyEmailAddressToClipboard": "Copy email address",
        "copyIMAddressToClipboard": "Copy chat address",
        "copyWebPageToClipboard": "Copy web page url",
        "emptyChatList": "There's no information to show here.",
        "emptyPhoneList": "We don't have a phone number to show.",
        "emptyLocationList": "We don't have an address to show.",
        "phoneLinkTitle": "Call {0} on {1}: {2}",
        "emailLinkTitle": "Send email to {1}",
        "chatLinkTitle": "Start chat with {0}",
        "webPageTitle": "Open {0} in a new window",
        "businessAddress": "Business address",
        "homeAddress": "Home address",
        "otherAddress": "Other address",
        "webPage": "Web page",
        "personalWebPage": "Personal web page",
        "personalNotes": "Notes",
        "personalNotesPlaceholder": "Add notes",
        "sourceDirectory": "Directory",
        "sourceContact": "Contact"
      },
      "immersiveProfileOofStrings": {
        "outOfOffice": "{0} is sending automatic replies:",
        "showMore": "Show more"
      },
      "immersiveProfilePersonalInfoStrings": {
        "name": "Name",
        "nickname": "Nickname",
        "company": "Company",
        "department": "Department",
        "fullName": "Full name",
        "jobTitle": "Job title",
        "officeLocation": "Office location",
        "manager": "Manager",
        "assistant": "Assistant",
        "significantOther": "Significant other",
        "birthday": "Birthday",
        "anniversary": "Anniversary",
        "copyNameToClipboard": "Copy name",
        "copyNickNameToClipboard": "Copy nickname",
        "copyDepartmentToClipboard": "Copy department",
        "copyOfficeLocationToClipboard": "Copy location",
        "copyPostalAddressToClipBoard": "Copy address",
        "copyCompanyToClipboard": "Copy company",
        "copyJobTitleToClipboard": "Copy job title",
        "copyManagerToClipboard": "Copy manager",
        "copyAssistantToClipboard": "Copy assistant",
        "copySignificantOtherToClipboard": "Copy significant other",
        "copyBirthdayToClipboard": "Copy birthday",
        "copyAnniversaryToClipboard": "Copy anniversary date"
      },
      "immersiveProfileErrorStrings": {
        "somethingWentWrong": "Something went wrong.",
        "tryAgain": "Try again?"
      }
    },
    "immersiveProfileFileSectionStrings": {
      "fileLocationHoverText": "Go to file location",
      "openEmailHoverText": "Open email",
      "copyLink": "Copy link",
      "clearFilter": "Clear filter",
      "filterPlaceholder": "Type to filter",
      "title": "Recent files",
      "titleYou": "Your recent files",
      "titleWithAttachments": "Recent files and email attachments",
      "titleYouWithAttachments": "Your recent files and email attachments",
      "shortTitle": "Files",
      "oneDriveTitle": "{0}'s OneDrive",
      "noFilesFound": "Nothing here matches your search.",
      "noFilesFoundWithDefaultFilterYou": "Seems like you haven’t stored any files in Office 365. When you upload files to OneDrive or SharePoint, you’ll also see them here.",
      "noFilesFoundWithDefaultFilterOther": "Seems like {0} hasn't shared anything with you lately.",
      "learnMore": "Learn more.",
      "loadingFiles": "We're getting the files for you. This shouldn't take long.",
      "modified": "Modified",
      "sentToYou": "Sent to you",
      "attachmentFromOutlook": "Outlook",
      "documentFromOneDrive": "OneDrive",
      "documentFromSharepoint": "Sharepoint",
      "documentIsShared": "Shared document",
      "immersiveProfileFileSelectorStrings": {
        "all": "All",
        "attachments": "Email attachments",
        "word": "Word",
        "excel": "Excel",
        "powerPoint": "PowerPoint",
        "oneNote": "OneNote",
        "pdf": "PDF",
        "filter": "Filter",
        "typeToFilter": "Start typing to filter the list",
        "buttonAriaLabel": "Filter for file types, click here to view options",
        "filterFileTypeAriaLabel": "This file type only"
      }
    },
    "immersiveProfileEmailsSectionStrings": {
      "shortTitle": "Email",
      "emailsTitle": "Recent email",
      "attachmentsTitle": "Attachments",
      "senderLabelIncoming": "{0} to you",
      "senderLabelOutgoing": "You to {0}",
      "senderLabelIncomingAdditionalRecipients": "{0} to you + {1} more",
      "senderLabelOutgoingAdditionalRecipients": "You to {0} + {1} more",
      "emptyEmailsMessage": "We couldn't find any emails between you and {0}.",
      "emptyEmailsMessageMe": "We couldn't find any emails.",
      "emailsLoadingMessage": "We're getting the emails for you. This shouldn't take long.",
      "noEmailsAttachmentsMessage": "We couldn't find any email attachments between you and {0}.",
      "noEmailsAttachmentsForYourselfMessage": "We couldn't find any email attachments for you.",
      "attachmentsAreLoadingMessage": "We are currently loading the attachments between you and {0}.",
      "seeMoreAttachments": "See more"
    },
    "immersiveProfileOrganizationSectionStrings": {
      "title": "Organization",
      "organization": "See who {0} works with",
      "managerChainAriaLabel": "Manager chain for {0}",
      "directReportsAriaLabel": "People reporting to {0} ({1})",
      "directReportsYouAriaLabel": "People reporting to you ({0})",
      "focusedPersonAriaLabel": "Information about {0}",
      "worksWithAriaLabel": "Works with",
      "showMorePeople": "See more",
      "somethingWentWrong": "Something went wrong.",
      "tryAgain": "Try again?",
      "noOrgSectionDescriptionOther": "We don't have the details to show the organization chart for {0}. Organization details are provided by your admin or human resources department.",
      "noOrgSectionDescriptionSelf": "We don't have the details to show your organization chart. Organization details are provided by your admin or human resources department.",
      "noOrgSectionLink": "How do I find out who my admin is?"
    },
    "immersiveProfileMeetingsSectionStrings": {
      "header": "Type to filter meetings",
      "title": "Meetings",
      "clearFilter": "Clear filter",
      "filterPlaceholder": "Type to filter",
      "immersiveProfileMeetingSelectorStrings": {
        "all": "All",
        "attachments": "Attachments",
        "typeToFilter": "Start typing to filter the list"
      }
    },
    "immersiveProfileConversationsSectionStrings": {
      "title": "Conversations",
      "header": "Type to filter conversations",
      "clearFilter": "Clear filter",
      "filterPlaceholder": "Type to filter",
      "immersiveProfileConversationSelectorStrings": {
        "all": "All",
        "to": "To",
        "from": "From",
        "typeToFilter": "Start typing to filter the list"
      }
    },
    "immersiveProfileLinkedInSectionStrings": {
      "title": "LinkedIn",
      "viewInLinkedInButtonText": "See full profile on LinkedIn",
      "viewInLinkedInButtonTextAriaLabel": "See full profile on LinkedIn. Opens in a new browser tab",
      "highlights": "Highlights",
      "education": "Education",
      "experience": "Experience",
      "previousExperience": "Previous experience",
      "hoverUnderlineAriaLabel": "View {0} on LinkedIn. Opens in new browser tab",
      "seeMoreOnLinkedIn": "{0} more on LinkedIn",
      "ariaOneMoreEducationOnLinkedIn": "1 more education on Linkedin. Opens in new browser tab",
      "ariaMoreEducationsOnLinkedIn": "{0} more educations on Linkedin. Opens in new browser tab",
      "ariaOneMoreExperienceOnLinkedIn": "1 more experience on Linkedin. Opens in new browser tab",
      "ariaMoreExperiencesOnLinkedIn": "{0} more experiences on Linkedin. Opens in new browser tab",
      "backToSearchResultsButtonText": "Back to matches",
      "removeAssociationText": "Wrong LinkedIn profile",
      "removeAssociationForMeText": "Not my LinkedIn profile",
      "reportProfile": "Report profile to LinkedIn",
      "connectionCount": "{0} connection",
      "connectionsCount": "{0} connections",
      "connectionsCountMore": "{0}+ connections",
      "titleAndCompany": "{0} at {1}",
      "linkedInSearchViewSingleResultTitle": "{0} possible profile match",
      "linkedInSearchViewTitle": "{0} possible profile matches",
      "linkedInSearchViewTitleInCard": "LinkedIn matches",
      "associationText": "Is this the right match?",
      "associationForMeText": "Is this your profile?",
      "noLinkedInProfilesMessage": "Seems like {0} hasn’t created a LinkedIn profile yet, or they are not sharing their profile information.",
      "noLinkedInProfilesMessageForYou": "We couldn't find a LinkedIn profile for you.",
      "nothingToShowTitle": "Nothing to show",
      "nothingToShowDetails": "We can't show any experience or education information from LinkedIn for {0}. You might find other information if you go to LinkedIn.",
      "onlyMatchFromLinkedIn": "We could only find one profile match for {0}",
      "feedbackMessage": "We need your help to make this LinkedIn feature better.",
      "loadingLinkedInProfiles": "We're getting LinkedIn Profiles for {0}. This shouldn't take long.",
      "loadingLinkedInProfilesForYou": "We're getting LinkedIn Profiles for you. This shouldn't take long.",
      "linkedInDateSpanToDate": "{0} – Present",
      "linkedInStartEndTerms": "{0} – {1}",
      "linkedInMonthYear": "{0} {1}",
      "profileLinkedText": "Profile has been linked",
      "undoAssociationText": "Undo",
      "linkedInAndO365BindButtonText": "Yes, let's go",
      "bindUpsellText1": "Sign in to LinkedIn and we’ll",
      "bindUpsellText1Continuation": "show profile info here",
      "bindUpsellText2": "You only have to do this once.",
      "bindExperienceIllustrationText": "See people's experience",
      "bindMutualConnectionsIllustrationText": "Discover mutual connections",
      "bindConnectIllustrationText": "Connect with people",
      "bindNotMemberText": "Not on LinkedIn?",
      "bindJoinNowText": "Join now",
      "showMoreMatches": "Show {0} more matches",
      "noMoreMatches": "No more matches",
      "thankYouForFeedback": "Thank you for your feedback",
      "associationYesAltText": "Yes",
      "associationNoAltText": "No",
      "connect": "Connect",
      "connectScreenReaderText": "Connect to {0}",
      "acceptInvitation": "Accept",
      "acceptInvitationScreenReaderText": "Accept LinkedIn Invitation from {0}",
      "sendingInvitation": "Sending",
      "sendingInvitationScreenReaderText": "Sending LinkedIn invitation to {0}",
      "invitationSent": "Invitation sent",
      "invitationPending": "Pending",
      "invitationPendingScreenReaderText": "Invitation pending from {0}",
      "firstDegreeConnection": "1st",
      "secondDegreeConnection": "2nd",
      "thirdDegreeConnection": "3rd",
      "linkedInProfileMatched": "LinkedIn profile matched.",
      "clickToMatchLinkedInProfile": "Choose the matching profile",
      "clickToMatchSingleLinkedInProfile": "Choose the matching profile",
      "connectButtonAltText": "Send invitation to connect on LinkedIn",
      "acceptLinkedInInvitationButtonAltText": "Accept LinkedIn invitation",
      "pendingLinkedInInvitationButtonAltText": "Awaiting answer from {0}",
      "sendingLinkedInInvitationAltText": "Sending invitation to connect on LinkedIn",
      "linkedInDisclaimerText": "Some LinkedIn profiles may not be shown due to individual privacy settings",
      "institutionLogoScreenReaderText": "Institution logo",
      "sharedConnectionsScreenReaderText": "Shared connections",
      "linkedInDegreeAndFieldOfStudy": "{0}, {1}",
      "associationErrorText": "Something went wrong",
      "associationTryAgainText": "Try again",
      "mutualConnections": "{0}:",
      "experienceWithSeparator": "Experience:",
      "salesNavTeamlinkConnections": "TeamLink Connections",
      "salesNavigator": "Sales Navigator",
      "saveAsLead": "Save as Lead",
      "saveAsLeadScreenreaderText": "Save {0} as lead",
      "saveAsLeadAltText": "Save profile as sales lead.",
      "unsaveAsLead": "Unsave as Lead",
      "unsaveAsLeadScreenreaderText": "Unsave {0} as lead",
      "unsaveAsLeadAltText": "Unsave profile as sales lead.",
      "isSavedAsLead": "Saved as lead",
      "saveAsLeadWithoutAccount": "Save without account"
    },
    "immersiveProfileUserGroupMembershipSectionStrings": {
      "panelTitle": "{0} Memberships",
      "tabTitle": "Memberships"
    },
    "immersiveProfileDistributionListOverviewSectionStrings": {
      "title": "About",
      "immersiveProfileDistributionListOverviewStrings": {
        "distributionListOverview": "About this distribution list",
        "description": "Description",
        "distributionListMembers": "Distribution list members"
      },
      "immersiveProfileDistributionListMembersStrings": {
        "membersCountDistributionList": "+{0} others"
      }
    },
    "immersiveProfileDistributionListMembersSectionStrings": {
      "title": "Members",
      "sectionHeader": "All members",
      "immersiveProfileDistributionListMembersStrings": {
        "ownersTitle": "Owners",
        "membersTitle": "Members",
        "membersCountDistributionList": "+{0} others"
      }
    }
  },
  "teamlinkConnectionHighlightStrings": {
    "sharedConnection": "{0} Teamlink connection",
    "sharedConnections": "{0} Teamlink connections",
    "sharedConnectionsDetailOneConnectionWithoutVieweeName": "You both know {0}",
    "sharedConnectionsDetailOneConnection": "You and {0} both know {1}",
    "sharedConnectionsDetailTwoConnections": "You and {0} both know {1} and {2}",
    "sharedConnectionsDetailThreeConnections": "You and {0} both know {1}, {2}, and {3} other",
    "sharedConnectionsDetailMoreThanThreeConnections": "{0}, {1}, {2} and {3} others"
  },
  "sharedConnectionHighlightStrings": {
    "sharedConnection": "{0} mutual connection",
    "sharedConnections": "{0} mutual connections",
    "sharedConnectionsDetailOneConnection": "You and {0} both know {1}",
    "sharedConnectionsDetailTwoConnections": "You and {0} both know {1} and {2}",
    "sharedConnectionsDetailThreeConnections": "You and {0} both know {1}, {2}, and {3} other",
    "sharedConnectionsDetailMoreThanThreeConnections": "You and {0} both know {1}, {2}, and {3} others"
  },
  "sharedExperienceHighlightStrings": {
    "sharedExperience": "You both worked at {0}"
  },
  "sharedEducationHighlightStrings": {
    "sharedEducation": "You both studied at {0}"
  },
  "workAnniversaryHighlightStrings": {
    "workAnniversarySingular": "{0} completed 1 year at {1}",
    "workAnniversaryPlural": "{0} completed {1} years at {2}"
  },
  "birthdayHighlightStrings": {
    "wishBirthday": "Wish {0} a happy birthday ({1} {2})"
  },
  "positionChangeHighlightStrings": {
    "positionChange": "Started a new position",
    "companyChange": "Started a new job"
  },
  "contactEditorStrings": {
    "save": "Save",
    "edit": "Edit",
    "remove": "Remove",
    "cancel": "Cancel",
    "saving": "Saving",
    "create": "Create",
    "tryAgain": "Try again",
    "discard": "Discard",
    "closeButtonAccessibilityTitle": "Close",
    "attributionsAriaLabel": "Show information source",
    "saveDialogTitle": "You’re about to leave a page with unsaved changes",
    "saveDialogSubText": "Do you want to save? ",
    "errorSaveFailed": "We couldn’t save your changes.",
    "errorSaveModifyFailedNewContact": "We’ve saved your contact, but can’t show the changes just yet.",
    "errorSaveModifyFailedExistingContact": "We’ve saved your changes to the contact, but can’t show the changes just yet.",
    "errorSavePictureFailedNewContact": "We’ve saved your contact, but couldn’t save the photo. Try uploading the photo once more.",
    "errorSavePictureFailedExistingContact": "We’ve saved your changes to the contact, but couldn’t save the photo. Try uploading the photo once more.",
    "saveErrorDialogTitleEmailError": "Check email address",
    "saveErrorDialogTextEmailError": "Seems like you entered an email address that’s not valid",
    "loadErrorDialogTitle": "We’re having trouble opening the contact. Try refreshing the page or try again later.",
    "saveDialogYes": "Save",
    "saveDialogNo": "Don’t save",
    "saveDialogCancel": "Cancel",
    "errorDialogCancel": "Cancel",
    "errorDialogClose": "Close",
    "emailErrorMessage": "Use this format: someone@example.com",
    "navigationWarning": "You have unsaved content",
    "addToFavorites": "Add to favorites",
    "removeFromFavorites": "Remove from favorites",
    "attributionsCaption": "Found in:",
    "contactEditFormAriaLabel": "Contact Edit Form",
    "contactInformation": "Contact information",
    "workDetailsHeader": "Work",
    "postalAddressesHeader": "Address",
    "otherPropertiesHeader": "Other",
    "privateNotes": "Notes",
    "privateNotesSection": "Notes ({0})",
    "privateNotesPlaceholder": "Add notes",
    "addMore": "Add more",
    "labelAddNameSubmenu": "Name",
    "labelAddPhoneSubmenu": "Phone",
    "labelAddPhoneOtherSubmenu": "Other",
    "labelAddAddressSubmenu": "Address",
    "labelAddWorkSubmenu": "Work",
    "labelAddOtherSubmenu": "Other",
    "labelGivenName": "First name",
    "labelMiddleName": "Middle name",
    "labelSurname": "Last name",
    "labelDisplayNamePrefix": "Title",
    "labelGeneration": "Suffix",
    "labelNickname": "Nickname",
    "labelYomiName": "Yomi name",
    "labelYomiFirstName": "Yomi first name",
    "labelYomiLastName": "Yomi last name",
    "labelPersonaBodies": "Notes",
    "labelCompanyName": "Company",
    "labelDepartment": "Department",
    "labelLocation": "Office location",
    "labelTitle": "Job title",
    "labelYomiCompanyName": "Yomi company",
    "labelEmail": "Email",
    "labelAssistant": "Assistant phone",
    "labelBusiness": "Business phone",
    "labelAddBusiness": "Business",
    "labelBusinessFax": "Business fax",
    "labelCallback": "Callback phone",
    "labelHome": "Home phone",
    "labelAddHome": "Home",
    "labelHomeFax": "Home fax",
    "labelMobile": "Mobile phone",
    "labelAddMobile": "Mobile",
    "labelOrganizationMain": "Organization main",
    "labelOther": "Other",
    "labelIM": "Chat",
    "labelOtherFax": "Other fax",
    "labelPager": "Pager",
    "labelPrimary": "Primary",
    "labelRadio": "Radio phone",
    "labelTelex": "Telex",
    "labelTTYTDD": "TTY",
    "labelOfficeLocation": "Office Location",
    "labelPersonaDepartment": "Department",
    "labelPersonaManagers": "Manager",
    "labelPersonaBusinessHomePages": "Web page",
    "labelPersonaAssistantNames": "Assistant",
    "labelPersonaLocations": "Location",
    "labelPersonaHobbies": "Hobbies",
    "labelPersonaSchools": "School",
    "labelPersonaHomeAddresses": "Home address",
    "labelAddPersonaHomeAddresses": "Home",
    "labelPersonaBusinessAddresses": "Business address",
    "labelAddPersonaBusinessAddresses": "Business",
    "labelPersonaOtherAddresses": "Other address",
    "labelAddPersonaOtherAddresses": "Other",
    "labelStreet": "Street",
    "labelCity": "City",
    "labelStateProvince": "State/Province",
    "labelZipPostalCode": "Zip/Postal code",
    "labelCountryRegion": "Country/Region",
    "labelPersonaPersonalHomePages": "Personal web page",
    "labelPersonaSpouseNames": "Significant other",
    "labelPersonaWeddingAnniversaries": "Anniversary",
    "labelPersonaBirthdays": "Birthday",
    "labelGoToToday": "Go to today",
    "labelGoToPreviousMonth": "Go to previous month",
    "labelGoToNextMonth": "Go to next month",
    "labelGoToPrevYear": "Go to previous year",
    "labelGoToNextYear": "Go to next year",
    "labelSelectDay": "Select a day...",
    "contactEditorDayNamesStrings": {
      "monday": "Monday",
      "tuesday": "Tuesday",
      "wednesday": "Wednesday",
      "thursday": "Thursday",
      "friday": "Friday",
      "saturday": "Saturday",
      "sunday": "Sunday"
    },
    "contactEditorDayShortNamesStrings": {
      "monday": "M",
      "tuesday": "T",
      "wednesday": "W",
      "thursday": "T",
      "friday": "F",
      "saturday": "S",
      "sunday": "S"
    },
    "contactEditorDatePickerLocale": "en-US",
    "labelDay": "Day",
    "labelMonth": "Month",
    "labelYear": "Year",
    "infoTextNewContact": {
      "title": "New contact",
      "description": "You can add more information than what you see here, such as address and birthday. Select {0} to bring up more options."
    },
    "infoTextAddContact": {
      "title": "Add contact",
      "description": "You can add more information than what you see here, such as address and birthday. Select {0} to bring up more options."
    },
    "infoTextEditContact": {
      "title": "Edit contact",
      "description": "You can add more information than what you see here, such as address and birthday. Select {0} to bring up more options."
    },
    "infoTextEditLinkedContact": {
      "title": "Edit linked contact",
      "description": "You can add more information than what you see here, such as address and birthday. Select {0} to bring up more options.\n\nChanges will be saved to all linked contacts.",
      "subTitle": "Why can't I edit?",
      "subDescription": "You may not be able to edit all information. Point your mouse to the {0} icon that appears on hover to see where the information is from."
    },
    "profilePhotoPickerStrings": {
      "cancel": "Cancel",
      "upload": "Upload a photo",
      "uploadHeader": "Change contact photo",
      "inProgress": "In progress...",
      "close": "Done",
      "apply": "Apply",
      "remove": "Remove",
      "imageTooSmall": "This photo is very small and may look blurry on larger screens. Do you have a bigger one?",
      "notAnImage": "Hmm... that file format didn't work. Try using one of the more common image formats, such as .jpg, .png, or .gif.",
      "somethingWentWrong": "The photo couldn’t be uploaded at this time. Please try again.",
      "unsupportedBrowser": "Your browser does unfortunately not appear to support HTML5",
      "dropZone": "Drag your photo here",
      "zoom": "Zoom",
      "zoomOut": "Zoom out",
      "zoomIn": "Zoom in",
      "success": "Successfully set contact photo"
    }
  },
  "userGroupMembershipBlockStrings": {
    "title": "Membership",
    "titleYou": "Your group memberships",
    "footer": "Show list of group membership"
  }
};